name: "build-test"
on: # rebuild any PRs and main branch changes
  push:
    branches:
      - windows

jobs:
  build: # make sure build/ci work properly
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: TheMrMilchmann/install-jdk@v1
      with:
        version: '11'
        targets: 'JDK_11'
    - run: SET
    - name: AQA
      uses: ./
      with: 
        version: '11'
        jdksource: 'customized'
        build_list: 'functional'
        target: '_floatSanityTests'